#!/bin/sh
if [ -z "$1" ];then
echo "nothing to do. which instance are we launching?"
exit 1
fi
if [ "$2" != "on" ];then
echo "syntax-error. cosgo-launch <namehere> on <portnumber>."
exit 1
fi
if [ -z "$3" ];then
echo "need port number."
exit 1
fi

sudo -u $1 pkill -u $1 cosgo
#MANDRILL_KEY=feZKGMMFNGeoXz8Jo--0SQ CASGO_DESTINATION=aerth@isupon.us /demon/$1/cosgo -insecure -fastcgi -port $3 > /dev/null 2>&1
cd /demon/$1/
sudo -u $1 MANDRILL_KEY=feZKGMMFNGeoXz8Jo--0SQ CASGO_DESTINATION=aerth@isupon.us nohup /demon/$1/cosgo -insecure -fastcgi -port $3 $4
