#!/bin/sh
if [ -z "$1" ];then

echo "no execute"
echo "COSGOPORT=8080 update-casgo namehere"
exit 1
fi

echo Updating $1
sleep 5
echo Starting!
cd /demon/$1
sudo -u $1 GOPATH=/demon/$1/go go get -v -u github.com/aerth/cosgo
sudo -u $1 mv cosgo cosgo-old
sudo -u $1 cp go/bin/cosgo .
echo Upgraded $1.
echo Killing process
sudo -u $1 pkill -u $1 cosgo

echo Starting cosgo
sudo -u $1 cosgo-launch $1 on $(echo $COSGOPORT)
cosgo-launch $1 on $(echo $COSGOPORT)
echo Cosgo upgrade complete. Thanks for using free software!
